-- Active: 1701697030316@@127.0.0.1@5432@ai-chat-db@public
-- Generated by the database client.
CREATE TABLE answers(
    uuid uuid NOT NULL DEFAULT uuid_generate_v1(),
    creator_uuid uuid NOT NULL,
    question uuid NOT NULL,
    title text,
    content text,
    time_elapsed time without time zone NOT NULL DEFAULT '00:00:00'::time without time zone,
    quality integer NOT NULL DEFAULT 1,
    trust integer NOT NULL DEFAULT 1,
    date_created timestamp without time zone NOT NULL DEFAULT now(),
    date_updated timestamp without time zone NOT NULL DEFAULT now(),
    source_type varchar(256) NOT NULL DEFAULT 'model'::character varying,
    user_uuid uuid
);
COMMENT ON COLUMN answers.question IS 'the question to this answer';
COMMENT ON COLUMN answers.title IS 'short version of answer';
COMMENT ON COLUMN answers.content IS 'long version of answer';
COMMENT ON COLUMN answers.quality IS 'how good is the answer over all';
COMMENT ON COLUMN answers.trust IS 'would give this answer to someone else?';
COMMENT ON COLUMN answers.source_type IS 'human, model, external';

ALTER TABLE answers ADD CONSTRAINT answers_pkey PRIMARY KEY (uuid);
ALTER TABLE answers ADD CONSTRAINT answers_creator_uuid_fkey FOREIGN KEY (creator_uuid) REFERENCES users(uuid);
ALTER TABLE answers ADD CONSTRAINT answers_question_fkey FOREIGN KEY (question) REFERENCES questions(uuid);
ALTER TABLE answers ADD CONSTRAINT answers_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES users(uuid);
```
Change Owner to ai-chat-pguser
```SQL
ALTER TABLE answers OWNER TO "ai-chat-pguser";
